[configuration]
entry_symbol = "gdext_rust_init"
compatibility_minimum = 4.1
reloadable = true

[libraries]
linux.debug.x86_64 =     "res://{{path}}/target/debug/lib{{name}}.so"
linux.release.x86_64 =   "res://{{path}}/target/release/lib{{name}}.so"
windows.debug.x86_64 =   "res://{{path}}/target/debug/{{name}}.dll"
windows.release.x86_64 = "res://{{path}}/target/release/{{name}}.dll"
macos.debug =            "res://{{path}}/target/debug/lib{{name}}.dylib"
macos.release =          "res://{{path}}/target/release/lib{{name}}.dylib"
macos.debug.arm64 =      "res://{{path}}/target/debug/lib{{name}}.dylib"
macos.release.arm64 =    "res://{{path}}/target/release/lib{{name}}.dylib"